server:
  port: 8100
  servlet:
    context-path: /board-service

spring:
  application:
    name: board-service

logging:
  config: classpath:log/logback-spring.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka